import type { Match } from "@/app/components/MatchCard";

/* ============================================================
   MOCK DATA – Beautifully crafted dummy data for UI development
   ============================================================ */

export const MOCK_MATCHES: Record<string, Match[]> = {
  "over-1.5": [
    {
      id: "o15-1",
      homeTeam: "Arsenal",
      awayTeam: "Chelsea",
      homeTeamLogo: "🔴",
      awayTeamLogo: "🔵",
      matchTime: "15:00",
      league: "Premier League",
      confidence: 87,
      odds: 1.35,
      prediction: "Over 1.5 Goals",
    },
    {
      id: "o15-2",
      homeTeam: "Barcelona",
      awayTeam: "Real Madrid",
      homeTeamLogo: "🟠",
      awayTeamLogo: "⚪",
      matchTime: "20:00",
      league: "La Liga",
      confidence: 92,
      odds: 1.22,
      prediction: "Over 1.5 Goals",
    },
    {
      id: "o15-3",
      homeTeam: "Bayern Munich",
      awayTeam: "Dortmund",
      homeTeamLogo: "🔴",
      awayTeamLogo: "🟡",
      matchTime: "17:30",
      league: "Bundesliga",
      confidence: 78,
      odds: 1.42,
      prediction: "Over 1.5 Goals",
    },
    {
      id: "o15-4",
      homeTeam: "Inter Milan",
      awayTeam: "AC Milan",
      homeTeamLogo: "🔵",
      awayTeamLogo: "🔴",
      matchTime: "19:45",
      league: "Serie A",
      confidence: 73,
      odds: 1.55,
      prediction: "Over 1.5 Goals",
    },
    {
      id: "o15-5",
      homeTeam: "PSG",
      awayTeam: "Marseille",
      homeTeamLogo: "🔵",
      awayTeamLogo: "⚪",
      matchTime: "20:45",
      league: "Ligue 1",
      confidence: 85,
      odds: 1.28,
      prediction: "Over 1.5 Goals",
    },
    {
      id: "o15-6",
      homeTeam: "Liverpool",
      awayTeam: "Man City",
      homeTeamLogo: "🔴",
      awayTeamLogo: "🔵",
      matchTime: "16:30",
      league: "Premier League",
      confidence: 90,
      odds: 1.18,
      prediction: "Over 1.5 Goals",
    },
  ],

  "straight-win": [
    {
      id: "sw-1",
      homeTeam: "Man City",
      awayTeam: "Burnley",
      homeTeamLogo: "🔵",
      awayTeamLogo: "🟤",
      matchTime: "15:00",
      league: "Premier League",
      confidence: 94,
      odds: 1.15,
      prediction: "Man City Win",
    },
    {
      id: "sw-2",
      homeTeam: "Real Madrid",
      awayTeam: "Getafe",
      homeTeamLogo: "⚪",
      awayTeamLogo: "🔵",
      matchTime: "18:00",
      league: "La Liga",
      confidence: 89,
      odds: 1.25,
      prediction: "Real Madrid Win",
    },
    {
      id: "sw-3",
      homeTeam: "Bayern Munich",
      awayTeam: "Augsburg",
      homeTeamLogo: "🔴",
      awayTeamLogo: "🟢",
      matchTime: "14:30",
      league: "Bundesliga",
      confidence: 91,
      odds: 1.18,
      prediction: "Bayern Munich Win",
    },
    {
      id: "sw-4",
      homeTeam: "Juventus",
      awayTeam: "Empoli",
      homeTeamLogo: "⚪",
      awayTeamLogo: "🔵",
      matchTime: "19:45",
      league: "Serie A",
      confidence: 82,
      odds: 1.45,
      prediction: "Juventus Win",
    },
    {
      id: "sw-5",
      homeTeam: "PSG",
      awayTeam: "Lens",
      homeTeamLogo: "🔵",
      awayTeamLogo: "🔴",
      matchTime: "20:00",
      league: "Ligue 1",
      confidence: 86,
      odds: 1.3,
      prediction: "PSG Win",
    },
  ],

  "over-2.5": [
    {
      id: "o25-1",
      homeTeam: "Tottenham",
      awayTeam: "Newcastle",
      homeTeamLogo: "⚪",
      awayTeamLogo: "⚫",
      matchTime: "12:30",
      league: "Premier League",
      confidence: 76,
      odds: 1.65,
      prediction: "Over 2.5 Goals",
    },
    {
      id: "o25-2",
      homeTeam: "Bayer Leverkusen",
      awayTeam: "RB Leipzig",
      homeTeamLogo: "🔴",
      awayTeamLogo: "⚪",
      matchTime: "17:30",
      league: "Bundesliga",
      confidence: 81,
      odds: 1.5,
      prediction: "Over 2.5 Goals",
    },
    {
      id: "o25-3",
      homeTeam: "Barcelona",
      awayTeam: "Atletico Madrid",
      homeTeamLogo: "🟠",
      awayTeamLogo: "🔴",
      matchTime: "20:00",
      league: "La Liga",
      confidence: 68,
      odds: 1.85,
      prediction: "Over 2.5 Goals",
    },
    {
      id: "o25-4",
      homeTeam: "Napoli",
      awayTeam: "Roma",
      homeTeamLogo: "🔵",
      awayTeamLogo: "🟡",
      matchTime: "19:45",
      league: "Serie A",
      confidence: 72,
      odds: 1.72,
      prediction: "Over 2.5 Goals",
    },
  ],

  "over-3.5": [
    {
      id: "o35-1",
      homeTeam: "Arsenal",
      awayTeam: "Nottm Forest",
      homeTeamLogo: "🔴",
      awayTeamLogo: "🔴",
      matchTime: "15:00",
      league: "Premier League",
      confidence: 62,
      odds: 2.1,
      prediction: "Over 3.5 Goals",
    },
    {
      id: "o35-2",
      homeTeam: "Bayern Munich",
      awayTeam: "Mainz",
      homeTeamLogo: "🔴",
      awayTeamLogo: "⚪",
      matchTime: "14:30",
      league: "Bundesliga",
      confidence: 71,
      odds: 1.85,
      prediction: "Over 3.5 Goals",
    },
    {
      id: "o35-3",
      homeTeam: "Real Madrid",
      awayTeam: "Celta Vigo",
      homeTeamLogo: "⚪",
      awayTeamLogo: "🔵",
      matchTime: "18:00",
      league: "La Liga",
      confidence: 65,
      odds: 2.0,
      prediction: "Over 3.5 Goals",
    },
  ],

  btts: [
    {
      id: "btts-1",
      homeTeam: "Leeds United",
      awayTeam: "Aston Villa",
      homeTeamLogo: "⚪",
      awayTeamLogo: "🟤",
      matchTime: "15:00",
      league: "Premier League",
      confidence: 79,
      odds: 1.65,
      prediction: "Both Teams to Score",
    },
    {
      id: "btts-2",
      homeTeam: "Ajax",
      awayTeam: "Feyenoord",
      homeTeamLogo: "🔴",
      awayTeamLogo: "🟢",
      matchTime: "19:45",
      league: "Eredivisie",
      confidence: 83,
      odds: 1.52,
      prediction: "Both Teams to Score",
    },
    {
      id: "btts-3",
      homeTeam: "Lazio",
      awayTeam: "Fiorentina",
      homeTeamLogo: "🔵",
      awayTeamLogo: "🟣",
      matchTime: "17:00",
      league: "Serie A",
      confidence: 75,
      odds: 1.7,
      prediction: "Both Teams to Score",
    },
    {
      id: "btts-4",
      homeTeam: "Sevilla",
      awayTeam: "Real Betis",
      homeTeamLogo: "⚪",
      awayTeamLogo: "🟢",
      matchTime: "20:00",
      league: "La Liga",
      confidence: 77,
      odds: 1.62,
      prediction: "Both Teams to Score",
    },
    {
      id: "btts-5",
      homeTeam: "Monaco",
      awayTeam: "Lyon",
      homeTeamLogo: "🔴",
      awayTeamLogo: "🔵",
      matchTime: "20:45",
      league: "Ligue 1",
      confidence: 80,
      odds: 1.55,
      prediction: "Both Teams to Score",
    },
  ],
};
